name: ci 
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

# This gives the action permission to actually publish the site
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - run: pip install mkdocs-material mkdocs-jupyter
      
      # We just 'build' the site, we don't 'gh-deploy' it
      - run: mkdocs build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
